'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TutorialVB

    Partial Public Class [Default]

        '''<summary>
        '''DayPilotCalendar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DayPilotCalendar1 As Global.DayPilot.Web.Ui.DayPilotCalendar
    End Class
End Namespace
